version: '3.9'
services:
  proxy:
    image: nginx:latest
    volumes:
    # Mount the reverse_proxy_settings volume to the /etc/nginx directory
    - reverse_proxy_settings:/etc/nginx
    # Bind the ports to all available interfaces
    ports:
    - "80:80"
    - "443:443"
    extra_hosts:
    - "host.docker.internal:host-gateway"
volumes:
  reverse_proxy_settings:
    name: reverse_proxy_settings
  reverse_proxy_data:
    name: reverse_proxy_data